PROBLEM 1: Matrix product is calculated manually

In [1]:
For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The resulting matrix, known as the matrix product, 
has the number of rows of the first and the number of columns of the second matrix.

$c_{11} = -1 * 0 +2 * 0+ 3 *2 = 6$

....................

$c_{33} = 7 x 1 + 8 x (-8) + (-9) x (-1) = -48 $

SyntaxError: invalid syntax (<ipython-input-1-234882b1330e>, line 1)

PROBLEM 2: Calculation by NumPy function

In [26]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("Matrix product of A and B=\n{}".format(np.dot(a_ndarray,b_ndarray) ))

Matrix product of A and B=
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


PROBLEM 3: Implementation of calculation of a certain element

In [48]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

axb_ndarray=np.arange(len(a_ndarray)*len(b_ndarray[0])).reshape((len(a_ndarray),len(b_ndarray[0])))
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray)):
        axb_ndarray[i][j]=a_ndarray[i][0]*b_ndarray.T[j][0]+a_ndarray[i][1]*b_ndarray.T[j][1]+a_ndarray[i][2]*b_ndarray.T[j][2]
print("Matrix product of A and B=\n{}".format(axb_ndarray))

Matrix product of A and B=
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


PROBLEM 4: Creating a function that performs matrix multiplication

In [59]:
def matrix_funct(A,B):
    import numpy as np
    axb_ndarray=np.zeros(len(A)*len(B[0])).reshape(len(A),len(B[0]))
    for i in range(len(A)):
        for k in range(len(A[0])):
            for j in range(len(B)):
                axb_ndarray[i][k]+=A[i][j]*B.T[k][j]
    print("Matrix product of A and B=\n{}".format(axb_ndarray))

In [60]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
matrix_funct(A,B)

Matrix product of A and B=
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


PROBLEM 5: Judge the input whose calculation is not defined

In [64]:
def matrix_funct(A,B):
    import numpy as np
    if(len(A[0])!=len(B)):
        print(" The Product of Matrix A and B is not defined")
    else:
        axb_ndarray=np.zeros(len(A)*len(B[0])).reshape(len(A),len(B[0]))
        for i in range(len(A)):
            for k in range(len(A[0])):
                for j in range(len(B)):
                    axb_ndarray[i][k]+=A[i][j]*B.T[k][j]
        print("Matrix product of A and B=\n{}".format(axb_ndarray))

In [65]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
matrix_funct(d_ndarray_,e_ndarray)

 The Product of Matrix A and B is not defined


[Problem 6] Transposition

In [67]:
def matrix_funct(A,B):
    import numpy as np
    if(len(A[0])!=len(B)):
        print(" The Product of Matrix A and B is not defined")
    else:
        axb_ndarray=np.zeros(len(A)*len(B[0])).reshape(len(A),len(B[0]))
        for i in range(len(A)):
            for k in range(len(A[0])):
                for j in range(len(B)):
                    axb_ndarray[i][k]+=A[i][j]*B.T[k][j]
        print("Matrix product of A and B=\n{}".format(axb_ndarray))